workflows:
  build-apk:
    name: Build APK
    max_build_duration: 10
    environment:
      android:
        sdk: 34
    scripts:
      - name: Build APK with Gradle
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk